<?php
/**
 * Bambora Online 
 * 
 * @category    Online Payment Gatway
 * @package     Bambora_Online_Checkout
 * @author      Bambora
 * @copyright   Bambora (http://bambora.com)
 */
 
?>
<dl class="payment-method bambora_checkout">
  <p class="bambora_info_title">
    <?php echo $this->escapeHtml($this->getMethodTitle())?>
  </p>
  <p class="bambora_info_body">
    <?php echo $this->escapeHtml($this->getPaymentType())?>
  </p>
  <p class="bambora_info_body">
    <?php echo $this->escapeHtml($this->getTransactionId())?>
  </p>

</dl>

