<?php
/**
 * Copyright (c) 2017. All rights reserved Bambora Online.
 *
 * This program is free software. You are allowed to use the software but NOT allowed to modify the software.
 * It is also not legal to do any changes to the software and distribute it in your own name / brand.
 *
 * All use of the payment modules happens at your own risk. We offer a free test account that you can use to test the module.
 *
 * @author    Bambora Online
 * @copyright Bambora Online (http://bambora.com)
 * @license   Bambora Online
 *
 */

$specificInfo = $block->getSpecificInformation();
$paymentMethodTitle = $block->escapeHtml($block->getMethod()->getTitle());
$paymentInformationTitle = $block->getPaymentInformationTitle();
?>
<dl class="payment-method bambora_checkout">
  <dt class="title"><?php /* @noEscape */ echo $paymentMethodTitle; ?></dt>
<?php if ($specificInfo):?>
   <dt>
    <div style="margin-top:10px; margin-bottom:10px;">
        <h3><?php /* @noEscape */ echo $paymentInformationTitle; ?></h3>
        <table>
          <?php foreach ($specificInfo as $label => $value):?>
                  <tr>
                      <td><b><?php echo $block->escapeHtml($label)?>:</b></td>
                      <td style="padding-left:10px">
                          <?php /* @noEscape */ echo nl2br($block->escapeHtml(implode("\n", $block->getValueAsArray($value, true))));?>
                      </td>
                  </tr>
              <?php endforeach; ?>
        </table>
      </div>
   </dt>
<?php endif;?>
</dl>